# Configuration des entrées textuelles pour le karotz
input_text:
  karotz_ip_address:
    name: karotz Ip Address
    initial: "192.168.1.xxx" # Adresse IP par défaut du karotz
  karotz_color_1:
    name: karotz Color 1
    initial: "ffff00" # Couleur primaire en hexadécimal (jaune)
  karotz_color_2:
    name: karotz Color 2
    initial: "000000" # Couleur secondaire en hexadécimal (noir)
# tag RFID
  karotz_rfid_id:
    name: ID du tag RFID
  karotz_rfid_name:
    name: Nom du tag RFID
  karotz_rfid_url:
    name: URL à appeler

# État d'éveil du karotz
input_boolean:
  karotz_awake:
    initial: on
# active ou désactive l'ajout d'un tag rfid
  karotz_mode_enregistrement_tag:
    name: Enregistrement Tag karotz

# tag RFID
input_button:
  karotz_rfid_start_record:
    name: Démarrer l'enregistrement RFID
  karotz_rfid_stop_record:
    name: Arrêter l'enregistrement RFID
  karotz_rfid_refresh:
    name: Rafraîchir la liste des tags
  karotz_rfid_assign:
    name: Assigner le tag à une URL

# Configuration des contrôles numériques
input_number:
  karotz_ear_left:
    name: karotz Ear Left
    initial: 0
    min: 0
    max: 16 # Position maximale de l'oreille gauche
    step: 1
  karotz_ear_right:
    name: karotz Ear Right
    initial: 0
    min: 0
    max: 16 # Position maximale de l'oreille droite
    step: 1
  karotz_light_speed:
    name: karotz Light Speed
    initial: 700
    min: 0
    max: 2000 # Vitesse maximale des effets lumineux
    step: 100

# Groupement des contrôles karotz
group:
  karotz_utils:
    name: karotz Utils
    entities:
      - script.karotz_moods

# Scripts de contrôle du karotz
script:
  karotz_moods:
    alias: "Talk!" # Fait parler le karotz
    sequence:
      - action: rest_command.karotz_moods
  karotz_wakeup:
    alias: "Wake Up" # Réveille le karotz
    sequence:
      - action: rest_command.karotz_wakeup
      - action: rest_command.karotz_light
  karotz_sleep:
    alias: "Sleep" # Met le karotz en veille
    sequence:
      - action: rest_command.karotz_sleep
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.karotz_awake
# Apps du karotz
  karotz_tai_chi:
    alias: "Tai-Chi" # Fait faire du tai-chi au karotz
    sequence:
      - action: rest_command.karotz_tai_chi
# tag RFID
  karotz_assign_tag:
    alias: Assigner un tag RFID
    sequence:
      - action: rest_command.karotz_assign_tag

# Interrupteur template pour contrôler l'état d'éveil
switch:
  - platform: template
    switches:
      karotz_life:
        friendly_name: "Éveillé"
        value_template: "{{ is_state('input_boolean.karotz_awake', 'on') }}"
        turn_on:
          action: script.turn_on
          target:
            entity_id: script.karotz_wakeup
        turn_off:
          action: script.turn_on
          target:
            entity_id: script.karotz_sleep

# Configuration des commandes REST pour contrôler le karotz
# source : https://www.openkarotz.org/api/
rest_command:
  karotz_free_space:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/get_free_space" # espace mémoire utiliser
  karotz_moods:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/apps/moods" # dit une parole prés enregistrée aléatoire
  karotz_moods_id:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/apps/moods?id={{ moods_id }}" # dit une parole près enregistrée 1 à 305
  karotz_wakeup:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/wakeup?silent=1" # réveille en silence
  karotz_sleep:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/sleep" # dormir
  karotz_ears_random:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/ears_random" # position des oreilles alléatoires
  karotz_ears:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/ears?left={{ states('input_number.karotz_ear_left') }}&right={{ states('input_number.karotz_ear_right') }}&noreset=1" # position des oreilles
  karotz_ears_reset: 
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/ears_reset"
  karotz_light:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/leds?pulse=1&color={{ states('input_text.karotz_color_1') }}&speed={{ states('input_number.karotz_light_speed') }}&color2={{ states('input_text.karotz_color_2') }}" # allume la led et clignote
  karotz_light_fixed:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/leds?pulse=0color={{ states('input_text.karotz_color_1') }}" # allume la led fixe
  karotz_say:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/tts?voice=2&text={{ text }}&nocache=undefined" # Text to speeck, dit un du text
  karotz_sound:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/sound?id={{ sound }}" # jour un son près enregistré
# sounds : bip1,bling,flush,install_ok,jet1,laser_15,ready,rfid_error,rfid_ok,saut1,start,twang_01,twang_04,return":"0"
# Controle pour l'ajout des tag rfid
  karotz_rfid_record_start:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/rfid_start_record" # ajouter un nouveau tag rfid
  karotz_rfid_record_stop:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/rfid_stop_record" # arrêter l'ajout de tag rfid
  karotz_rfid_assign: # forge l'url pour l'ajout d'un tag rfid /cgi-bin/rfid_assign_url?tag=id du tag&url=url&name=nom de l'action
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/rfid_assign_url?tag={{ states('input_text.karotz_rfid_id') }}&url={{ states('input_text.karotz_rfid_url') | urlencode }}&name={{ states('input_text.karotz_rfid_name') | urlencode }}"
  karotz_rfid_list:
    url:  "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/rfid_list"
  karotz_rfid_list_ext:
    url:  "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/rfid_list_ext"
  karotz_rfid_delete:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/rfid_delete?tag={{ tag_id }}"
# Apps du karotz
  karotz_tai_chi:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/apps/tai-chi"
# Annonce de l'heure
  karotz_clock:
    url: "http://{{ states('input_text.karotz_ip_address') }}/cgi-bin/apps/clock"

# Capteur pour surveiller l'état de sommeil
sensor:
  - platform: rest
    resource: http://192.168.1.xxx/cgi-bin/status
    name: karotz_sleep_sensor
    value_template: "{{ value_json.sleep }}"
# tag RFID
  - platform: rest
    name: karotz_rfid_tags
    resource: "http://192.168.1.xxx/cgi-bin/rfid_list_ext"
    scan_interval: 5
    value_template: "{{ value_json.tags | to_json }}"
    json_attributes:
      - tags

# template:
#   - sensor:
#       - name: "Premier Tag RFID"
#         state: >
#           {% set tags = state_attr('sensor.karotz_rfid_tags', 'tags') %}
#           {{ tags[0].id if tags is iterable and tags|length > 0 else 'inconnu' }}
template:
  - sensor:
      - name: "Liste Tags RFID (Inversée)"
        state: "{{ now() }}"  # Juste pour forcer une mise à jour
        attributes:
          tags: >
            {% set tags = state_attr('sensor.karotz_rfid_tags', 'tags') %}
            {{ tags[::-1] if tags is iterable else [] }}


# Automatisations
automation:
  # Gestion de l'état d'éveil
  - id: karotz_on_automation
    alias: "karotz on"
    trigger:
      - trigger: state
        entity_id: sensor.karotz_sleep
        to: "0"
    actions:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.karotz_awake
      # - action: rest_command.karotz_say
      #   data:
      #     text: Bonjour tous le monde !

  - id: karotz_off_automation
    alias: "karotz off"
    trigger:
      trigger: state
      entity_id: sensor.karotz_sleep
      to: "1"
    actions:
      # - action: rest_command.karotz_say
      #   data:
      #     text: Bonne nuit les petits !
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.karotz_awake

  # Mise à jour des couleurs et effets lumineux
  - id: karotz_color_1_automation
    alias: "Update karotz color 1"
    trigger:
      trigger: state
      entity_id: input_text.karotz_color_1
    actions:
      - action: rest_command.karotz_light

  - id: karotz_color_2_automation
    alias: "Update karotz color 2"
    trigger:
      - trigger: state
        entity_id: input_text.karotz_color_2
    actions:
      - action: rest_command.karotz_light

  - id: karotz_color_speed_automation
    alias: "Update karotz light speed"
    trigger:
      - trigger: state
        entity_id: input_number.karotz_light_speed
    actions:
      - action: rest_command.karotz_light

  # Mise à jour de la position des oreilles
  - id: karotz_ear_left_automation
    alias: "Update karotz ear left"
    trigger:
      - trigger: state
        entity_id: input_number.karotz_ear_left
    actions:
      - action: rest_command.karotz_ears

  - id: karotz_ear_right_automation
    alias: "Update karotz ear right"
    trigger:
      - trigger: state
        entity_id: input_number.karotz_ear_right
    actions:
      - action: rest_command.karotz_ears

  # Annonce de l'heure toutes les heures
  - id: karotz_orloge_parlante_automation
    alias: "karotz bleu - Annonce de l'heure"
    description: "Fait annoncer l'heure par le karotz bleu toutes les heures"
    trigger:
      - trigger: time_pattern
        minutes: "0"
    condition:
      - condition: time
        after: "07:00:00"
        before: "20:00:00"
      - condition: state
        entity_id: input_boolean.karotz_awake
        state: "on"
    action:
      - action: rest_command.karotz_clock

# ajout des tag rfid
  - id: karotz_start_rfid_automation
    alias: Démarrer enregistrement karotz
    trigger:
      - trigger: state
        entity_id: input_boolean.karotz_mode_enregistrement_tag
        to: 'on'
    action:
      - action: rest_command.karotz_rfid_record_start

  - id: karotz_stop_rfid_automation
    alias: Arrêter enregistrement karotz
    trigger:
      - trigger: state
        entity_id: input_boolean.karotz_mode_enregistrement_tag
        to: 'off'
    action:
      - action: rest_command.karotz_rfid_record_stop

  - id: karotz_refrech_rfid_automation
    alias: Rafraîchir la liste des tags
    trigger:
      - trigger: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.karotz_rfid_refresh
    action:
      - action: rest_command.karotz_rfid_list_ext

  - id: karotz_asign_rfid_automation
    alias: Assigner le tag RFID à l'URL
    trigger:
      - trigger: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.karotz_rfid_assign
    action:
      - action: rest_command.karotz_rfid_assign

  - id: karotz_update_rfid_automation
    alias: Mise à jour de l'ID du tag
    trigger:
      - trigger: state
        entity_id: sensor.karotz_rfid_tags
    action:
      - action: input_text.set_value
        data_template:
          entity_id: input_text.karotz_rfid_id
          value: "{{ state_attr('sensor.karotz_rfid_tags', 'tags')[0].id if state_attr('sensor.karotz_rfid_tags', 'tags') | length > 0 else '' }}"