input_text:
  karotz_dev_ip_address:
    name: Karotz Dev IP Address
    initial: "192.168.1.xxx"
  karotz_dev_color_1:
    name: Karotz Dev Color 1
    initial: "ffff00"
  karotz_dev_color_2:
    name: Karotz Dev Color 2
    initial: "000000"
# Gestion des RFID ---------------------------------------
  karotz_dev_rfid_id:
    name: ID du tag
    initial: ""
  karotz_dev_rfid_name:
    name: Nom du tag
    initial: ""
  karotz_dev_rfid_url:
    name: URL du webhook
    initial: ""
  karotz_dev_rfid_delete_id:
    name: ID du tag à supprimer
    initial: ""
# TTS via home assistant ----------------------------------
  karotz_dev_tts_text_ha:
    name: Karotz TTS Text
    initial: "Bonjour je suis réveillé"

input_boolean:
  karotz_dev_awake:
    name: Karotz Dev Awake
    initial: true

input_number:
  karotz_dev_ear_left:
    name: Karotz Dev Ear Left
    initial: 0
    min: 0
    max: 16
    step: 1

  karotz_dev_ear_right:
    name: Karotz Dev Ear Right
    initial: 0
    min: 0
    max: 16
    step: 1

  karotz_dev_light_speed:
    name: Karotz Dev Light Speed
    initial: 700
    min: 0
    max: 2000
    step: 100

  karotz_dev_volume:
    name: Karotz Dev Volume
    min: 0
    max: 100
    step: 1
    mode: slider
    unit_of_measurement: "%"
    initial: 100

template:
  - sensor:
      - name: "Karotz Dev Volume (dB)"
        state: >
          {% set percentage = states('input_number.karotz_dev_volume') | float %}
          {% set db = ((100 - percentage) / 100 * -30) %}
          {{ db | round(0) }}
        unit_of_measurement: "dB"
        icon: mdi:volume-high
# RFID -----------------------------------------------------
      - name: "Karotz Dev RFID Tag List"
        state: >
          {% set tags = state_attr('sensor.karotz_dev_rfid_list_ext', 'tags') %}
          {% if tags %}
            OK
          {% else %}
            AUCUN
          {% endif %}
        attributes:
          list_markdown: >
            {% set tags = state_attr('sensor.karotz_dev_rfid_list_ext', 'tags') %}
            {% if tags %}
            | ID | Nom |
            |----|------|
            {% for tag in tags %}
            | {{ tag.id }} | {{ tag.name if tag.name else 'Sans nom' }} |
            {% endfor %}
            {% else %}
            Aucun tag trouvé
            {% endif %}

sensor:
  - platform: rest
    resource: "http://192.168.1.xxx/cgi-bin/status"
    name: karotz_dev_sleep_sensor
    value_template: "{{ value_json.sleep }}"

# Liste des tags RFID enregistrés ---------------------------------------
  - platform: rest
    name: karotz_dev_rfid_list_ext
    resource: "http://192.168.1.xxx/cgi-bin/rfid_list_ext"
    value_template: "{{ value_json.return }}"  # peu importe, juste pour remplir le state
    json_attributes:
      - tags
    scan_interval: 60

switch:
  - platform: template
    switches:
      karotz_dev_life:
        friendly_name: "Karotz Dev Awake"
        value_template: "{{ is_state('input_boolean.karotz_dev_awake', 'on') }}"
        turn_on:
          action: script.turn_on
          target:
            entity_id: script.karotz_dev_wakeup
        turn_off:
          action: script.turn_on
          target:
            entity_id: script.karotz_dev_sleep

rest_command:
  karotz_dev_free_space:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/get_free_space"
  karotz_dev_moods:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/apps/moods"
  karotz_dev_moods_id:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/apps/moods?id={{ moods_id }}"
  karotz_dev_wakeup:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/wakeup?silent=1"
  karotz_dev_sleep:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/sleep"
  karotz_dev_ears_random:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/ears_random"
  karotz_dev_ears:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/ears?left={{ states('input_number.karotz_dev_ear_left') }}&right={{ states('input_number.karotz_dev_ear_right') }}&noreset=1"
  karotz_dev_ears_reset: 
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/ears_reset"
  karotz_dev_light:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/leds?pulse=1&color={{ states('input_text.karotz_dev_color_1') }}&speed={{ states('input_number.karotz_dev_light_speed') }}&color2={{ states('input_text.karotz_dev_color_2') }}"
  karotz_dev_light_fixed:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/leds?pulse=0&color={{ states('input_text.karotz_dev_color_1') }}"
  karotz_dev_say:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/tts?voice=2&text={{ text }}&nocache=1"
  karotz_dev_say_ha:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/tts?voice=2&text={{ states('input_text.karotz_dev_tts_text_ha') | urlencode }}&nocache=0"
  karotz_dev_sound:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/sound?id={{ sound }}"
  karotz_dev_tai_chi:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/apps/tai-chi"
  karotz_dev_clock:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/apps/clock"
  karotz_dev_volume:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/volume?level={{ level }}"
    method: GET
# RFID ----------------------------------------------------
  karotz_dev_rfid_record_start:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/rfid_start_record"
  karotz_dev_rfid_record_stop:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/rfid_stop_record"
  karotz_dev_rfid_assign:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/rfid_assign_url?tag={{ states('input_text.karotz_dev_rfid_id') }}&url={{ states('input_text.karotz_dev_rfid_url') | urlencode }}&name={{ states('input_text.karotz_dev_rfid_name') | urlencode }}"
  karotz_dev_rfid_list:
    url:  "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/rfid_list"
  karotz_dev_rfid_list_ext:
    url:  "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/rfid_list_ext"
  karotz_dev_rfid_delete:
    url: "http://{{ states('input_text.karotz_dev_ip_address') }}/cgi-bin/rfid_delete?tag={{ states('input_text.karotz_dev_rfid_delete_id') }}"
# RFID ------------------------------------------------------
script:
  karotz_dev_assign_rfid:
    alias: Assigner un tag RFID
    sequence:
      - action: rest_command.karotz_dev_rfid_assign
  karotz_dev_delete_rfid:
    alias: Supprimer un tag RFID
    sequence:
      - action: rest_command.karotz_dev_rfid_delete
  karotz_dev_wakeup:
    sequence:
      - action: rest_command.karotz_dev_wakeup
  karotz_dev_sleep:
    sequence:
      - action: rest_command.karotz_dev_sleep
  karotz_dev_tai_chi:
    sequence:
      - action: rest_command.karotz_dev_tai_chi
  karotz_dev_moods:
    sequence:
      - action: rest_command.karotz_dev_moods

      
automation:
  - id: karotz_dev_on_automation
    alias: Karotz Dev On
    trigger:
      - trigger: state
        entity_id: sensor.karotz_dev_sleep_sensor
        to: "0"
    action:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.karotz_dev_awake

  - id: karotz_dev_off_automation
    alias: Karotz Dev Off
    trigger:
      - trigger: state
        entity_id: sensor.karotz_dev_sleep_sensor
        to: "1"
    action:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.karotz_dev_awake

  - id: karotz_dev_color_1_automation
    alias: Update Karotz Dev Color 1
    trigger:
      - trigger: state
        entity_id: input_text.karotz_dev_color_1
    action:
      - action: rest_command.karotz_dev_light

  - id: karotz_dev_color_2_automation
    alias: Update Karotz Dev Color 2
    trigger:
      - trigger: state
        entity_id: input_text.karotz_dev_color_2
    action:
      - action: rest_command.karotz_dev_light

  - id: karotz_dev_color_speed_automation
    alias: Update Karotz Dev Light Speed
    trigger:
      - trigger: state
        entity_id: input_number.karotz_dev_light_speed
    action:
      - action: rest_command.karotz_dev_light

  - id: karotz_dev_ear_left_automation
    alias: Update Karotz Dev Ear Left
    trigger:
      - trigger: state
        entity_id: input_number.karotz_dev_ear_left
    action:
      - action: rest_command.karotz_dev_ears

  - id: karotz_dev_ear_right_automation
    alias: Update Karotz Dev Ear Right
    trigger:
      - trigger: state
        entity_id: input_number.karotz_dev_ear_right
    action:
      - action: rest_command.karotz_dev_ears
