# <service_name> <sock_type> <proto> <flags> <user> <server_path> <args>
#21 stream tcp nowait root /bin/busybox ftpd -w /
#23 stream tcp nowait root /bin/busybox telnetd -i
80 stream tcp nowait root /bin/busybox httpd -i -c /karotz/etc/httpd.conf -h /usr/www
22 stream tcp nowait root /sbin/dropbear dropbear -i -B -R