[karotz]
ip_server=127.0.0.1
port_server=9123

url_update=http://127.0.0.1
url_app=http://127.0.0.1

domain_app=127.0.0.1
domain_update=127.0.0.1

lang=fr-FR
app_path=/usr/karotz/apps
log_path=/var/log/messages
log_level=0
asr_threshold=30

[k2k]
sipDomain=127.0.0.1

# a placer dans /etc/conf/ pour supprimer l'intéraction avec le site de karotz.nl