#!/bin/sh
# Mood 73 - Vache dans l'étang et marseillaise 
# Durée estimée : 10 secondes

# Inclusion des fichiers de configuration et fonctions
source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/ears.inc
source /usr/www/cgi-bin/leds.inc

# Position initiale
EarsReset

# LEDs : VIOLET et ORANGE en pulsation
/usr/www/cgi-bin/karotz/Leds 660099 FFA500 1 1 800

# Mouvement final si oreilles actives
if [ "$(cat /usr/www/cgi-bin/ears.disabled)" != "1" ]; then
    /usr/www/cgi-bin/karotz/EarsMove 6 6 200
    sleep 0.5
    /usr/www/cgi-bin/karotz/EarsMove -6 -6 200
    sleep 0.5
    /usr/www/cgi-bin/karotz/EarsReset
fi

# LEDs : vertes pour fin propre
/usr/www/cgi-bin/karotz/Leds 00FF00 000000 1 1 1000

exit 0
