#!/bin/bash
# Animation mood 86 - Myxomatose et lapins pas comestibles

# Inclusion des fichiers de configuration et fonctions
source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/ears.inc
source /usr/www/cgi-bin/leds.inc

# Position initiale
EarsReset

# LED orange fixe, un peu inquiétante
Leds FFA500 000000 0 1 1000
sleep 1

# Mouvement 1 : hésitation gauche/droite
EarsMove 10 4 60
Leds FFA500 000000 1 1 600
sleep 2

# Mouvement 2 : haut/bas confus
EarsMove 15 6 50
Leds FF0000 000000 1 1 400
sleep 2

# Mouvement 3 : petit tremblement nerveux
EarsMove 8 10 100
sleep 1.5
EarsMove 9 7 100
sleep 1

# Fin : repositionnement calme et LED verte
EarsReset
Leds 00FF00 000000 1 1 1000
sleep 1

DATA='{"return":"0","msg":"Mood 86 animation complete."}'
SendResponse "$DATA"
