#!/bin/bash
# Animation mood 101 - "Mail pas passé"

# Inclusion des fichiers de configuration et fonctions
source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/ears.inc
source /usr/www/cgi-bin/leds.inc

# Position initiale
EarsReset
Leds FF9900 000000 1 1 800  # LED orange trouble
sleep 1

# Mouvement de "pas bien" (oscille doucement)
EarsMove 8 12 60
sleep 1
EarsMove 12 8 60
sleep 1
EarsMove 7 13 60
sleep 1

# Clignotement rouge = erreur ? bug ?
Leds FF0000 000000 1 1 400
EarsMove 10 10 70
sleep 1

# Clignotement rapide puis retour
Leds FF0000 000000 1 1 300
EarsMove 6 6 70
sleep 1

# Retour au calme
EarsReset
Leds 00FF00 000000 1 1 1000
sleep 1

DATA='{"return":"0","msg":"Mood 101 animation complete."}'
SendResponse "$DATA"
