#!/bin/bash
# Animation Mood 16 : Hummm ! Y a pas moyen d'être tranquille, hein !

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/ears.inc

# Vérifie si le lapin est en veille
if [ -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, rabbit is sleeping."}'
    SendResponse "$DATA"
    exit 0
fi

# Vérifie si les oreilles sont désactivées
if [ -e "$CNF_DATADIR/Run/ears.disabled" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, ears disabled."}'
    SendResponse "$DATA"
    exit 0
fi

# LED rouge-orangée, pulsation rapide pour marquer l'agacement
Leds FF0000 FFA500 1 1 800

# Mouvement brusque des oreilles, comme un "grognement"
EarsMove 12 4 12
sleep 0.5
EarsMove 4 12 12
sleep 0.5
EarsMove 10 6 10
sleep 0.5
EarsMove 6 10 10
sleep 0.5

# Soupir / baisse des oreilles
EarsMove 3 3 8
sleep 1

# Retour à la normale, un peu sec
EarsReset

# LED verte rapide pour signaler la fin
Leds 00FF00 000000 1 1 800

# Réponse JSON
DATA='{"return":"0","msg":"Annoyed animation completed."}'
SendResponse "$DATA"
