#!/bin/bash
# Animation Mood 18 : Tada !! (2 secondes)

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/ears.inc

# LED rose + jaune, pulsation vive
Leds FFC0CB FFFF00 1 1 300

# Oreilles montent rapidement
EarsMove 15 15 20
sleep 0.5

# Petit effet d’éclat : pivot léger
EarsMove 13 17 18
sleep 0.5

# Retour à la normale
EarsReset

# LED verte fin d'animation
Leds 00FF00 000000 1 1 1000

