#!/bin/bash
# Animation Mood 15 : Gym rythmée (durée 15 secondes)

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/ears.inc

# Vérifie si le lapin est en veille
if [ -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, rabbit is sleeping."}'
    SendResponse "$DATA"
    exit 0
fi

# Vérifie si les oreilles sont désactivées
if [ -e "$CNF_DATADIR/Run/ears.disabled" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, ears disabled."}'
    SendResponse "$DATA"
    exit 0
fi

# LED rouge/jaune clignotantes pour l'énergie
Leds FF0000 FFFF00 1 1 400

# Boucle rythmique : 3 cycles "1 et 2", respire, puis 3 cycles
for i in 1 2 3; do
    EarsMove 14 2 10
    sleep 0.5
    EarsMove 2 14 10
    sleep 0.5
done

# Respire
EarsMove 8 8 6
sleep 1

# Reprise du rythme
for i in 1 2 3; do
    EarsMove 14 2 10
    sleep 0.5
    EarsMove 2 14 10
    sleep 0.5
done

# Ralentissement final
EarsMove 10 6 8
sleep 1

# Retour position neutre
EarsReset

# LED verte pour fin animation
Leds 00FF00 000000 1 1 1000

# Réponse JSON
DATA='{"return":"0","msg":"Gym animation completed."}'
SendResponse "$DATA"

