#!/bin/bash
# Mood 256 - Oreille douloureuse

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/ears.inc

# Vérifie si le lapin est en veille
if [ -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
    DATA='{"return":"1","msg":"Rabbit is sleeping."}'
    SendResponse "$DATA"
    exit 0
fi

# Vérifie si les oreilles sont désactivées
if [ -e "$CNF_DATADIR/Run/ears.disabled" ]; then
    DATA='{"return":"1","msg":"Ears disabled."}'
    SendResponse "$DATA"
    exit 0
fi

# LED rouge fixe pour signaler la "douleur"
Leds FF0000 000000 1 1 1000

# Oreille droite immobile, gauche qui "grince"
EarsMove 8 8 10
sleep 0.5
EarsMove 8 7 20
sleep 0.7
EarsMove 8 6 20
sleep 0.7
EarsMove 8 5 20
sleep 0.7
EarsMove 8 6 20
sleep 0.6
EarsMove 8 7 20
sleep 0.6
EarsMove 8 8 20
sleep 0.6

# LED orange pour signaler le retour au calme
Leds FF9900 000000 1 1 1000

EarsReset

DATA='{"return":"0","msg":"Mood 256 animation completed."}'
SendResponse "$DATA"
