#!/bin/bash
# Animation Mood 15 : Gym rythmée (durée 15 secondes)

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/ears.inc

# LED rouge/jaune clignotantes pour l’énergie
Leds FF0000 FFFF00 1 1 400

# Boucle rythmique : 3 cycles "1 et 2", respire, puis 3 cycles
for i in 1 2 3; do
    EarsMove 14 2 10
    sleep 0.5
    EarsMove 2 14 10
    sleep 0.5
done

# Respire
EarsMove 8 8 6
sleep 1

# Reprise du rythme
for i in 1 2 3; do
    EarsMove 14 2 10
    sleep 0.5
    EarsMove 2 14 10
    sleep 0.5
done

# Ralentissement final
EarsMove 10 6 8
sleep 1

# Retour position neutre
EarsReset

# LED verte pour fin animation
Leds 00FF00 000000 1 1 1000

