#!/bin/bash
# Animation par défaut : utilisée quand aucun ID de mood valide n'est fourni

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/ears.inc

# Position initiale
EarsReset

# LED cyan clignotante pour signal neutre/attente
Leds 00FFFF 00CCCC 1 1 1000

# Mouvements d’oreilles légers synchrones sur 4 secondes
EarsMove 8 8 15
sleep 0.6
EarsMove 6 6 15
sleep 0.6
EarsMove 7 7 15
sleep 0.6
EarsMove 5 5 15
sleep 0.6
EarsMove 8 6 15
sleep 0.6
EarsMove 6 8 15
sleep 0.6
EarsMove 7 7 15
sleep 0.4

# Retour à la position de repos
EarsReset

# LED verte pour indiquer que l’action est terminée
Leds 00FF00 000000 1 1 1000

