#!/bin/bash
# Animation "Alors c'était quoi déjà euh ?" pour le Karotz
# Oreilles qui bougent de manière hésitante

# Inclusion des fichiers de configuration et des fonctions utilitaires
source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/ears.inc
source /usr/www/cgi-bin/leds.inc

# Vérifie si le lapin est en veille
if [ -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, rabbit is sleeping."}'
    SendResponse "$DATA"
    exit 0
fi

# Vérifie si les oreilles sont désactivées
if [ -e "$CNF_DATADIR/Run/ears.disabled" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, ears disabled."}'
    SendResponse "$DATA"
    exit 0
fi

# Position initiale - oreilles légèrement inclinées
EarsMove 8 8 50
# LED jaune clignotante lente
Leds FFFF00 000000 1 1 800
sleep 2

# Premier moment d'hésitation (2-4s)
# Oreilles qui bougent lentement
EarsMove 6 10 40
# LED orange pulsante lente
Leds FF6600 000000 1 1 600
sleep 2

# Deuxième moment d'hésitation (4-6s)
# Oreilles qui s'inclinent de l'autre côté
EarsMove 10 6 40
# LED bleue pulsante
Leds 0000FF 000000 1 1 500
sleep 2

# Troisième moment d'hésitation (6-8s)
# Oreilles qui s'agitent légèrement
EarsMove 7 7 60
# LED violette pulsante rapide
Leds 9900FF 000000 1 1 400
sleep 2

# Quatrième moment d'hésitation (8-10s)
# Oreilles qui bougent de manière erratique
EarsMove 9 5 70
# LED verte pulsante très rapide
Leds 00FF00 000000 1 1 300
sleep 2

# Retour à la position initiale
EarsReset
# LED jaune fixe
Leds FFFF00 000000 1 1 1000
sleep 1

# Réponse JSON
DATA='{"return":"0","msg":"Hesitation animation completed."}'
SendResponse "$DATA" 