#!/bin/bash
# Animation Mood 8 : Et vous, euh, vous en pensez quoi de la réforme sur les garennes... (6s)

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/ears.inc

# LED violette (réflexion, sérieux)
Leds 660099 000000 1 1 600

# Mouvement lent gauche-droite comme si le lapin cherchait du regard
EarsMove 10 5 10
sleep 1
EarsMove 5 10 10
sleep 1
EarsMove 10 5 10
sleep 1
EarsMove 5 10 10
sleep 1

# Stop en "attente de réponse"
EarsMove 8 8 10
sleep 1

# Retour à la position initiale
EarsReset

# LED verte de fin
Leds 00FF00 000000 1 1 1000
