#!/bin/bash
# Animation Mood 17 : Hum ! J'ai faim ! Quand est-ce qu'on mange ? (4s)

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/ears.inc

# Vérifie si le lapin est en veille
if [ -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, rabbit is sleeping."}'
    SendResponse "$DATA"
    exit 0
fi

# Vérifie si les oreilles sont désactivées
if [ -e "$CNF_DATADIR/Run/ears.disabled" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, ears disabled."}'
    SendResponse "$DATA"
    exit 0
fi

# LED orange qui clignote, signe de demande / faim
Leds FFA500 FF0000 1 1 500

# Oreilles baissées = air boudeur / fatigué
EarsMove 5 5 10
sleep 0.5

# Petit mouvement nerveux
EarsMove 6 4 12
sleep 0.4
EarsMove 4 6 12
sleep 0.4

# Reprise
EarsMove 5 5 10
sleep 0.5

# Encore un petit "tic"
EarsMove 6 4 12
sleep 0.4
EarsMove 5 5 10
sleep 0.4

# Retour position neutre
EarsReset

# LED verte pour terminer
Leds 00FF00 000000 1 1 1000

# Réponse JSON
DATA='{"return":"0","msg":"Hungry animation completed."}'
SendResponse "$DATA"

