#!/bin/bash
# Animation "Hum ! Ça serait bien !" pour le Karotz
# Oreilles qui s'agitent avec enthousiasme

# Inclusion des fichiers de configuration et des fonctions utilitaires
source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/ears.inc
source /usr/www/cgi-bin/leds.inc

# Vérifie si le lapin est en veille
if [ -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, rabbit is sleeping."}'
    SendResponse "$DATA"
    exit 0
fi

# Vérifie si les oreilles sont désactivées
if [ -e "$CNF_DATADIR/Run/ears.disabled" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, ears disabled."}'
    SendResponse "$DATA"
    exit 0
fi

# Position initiale - oreilles droites
EarsReset
# LED rose fixe
Leds FF00FF 000000 1 1 1000
sleep 0.5

# Agitation des oreilles avec enthousiasme
EarsMove 12 12 50
# LED rose pulsante rapide
Leds FF00FF 000000 1 1 300
sleep 1

# Mouvement d'approbation
EarsMove 8 8 50
# LED rose pulsante moyenne
Leds FF00FF 000000 1 1 500
sleep 1

# Retour à la position initiale
EarsReset
# LED verte fixe
Leds 00FF00 000000 1 1 1000
sleep 0.5

# Réponse JSON
DATA='{"return":"0","msg":"Enthousiasme animation completed."}'
SendResponse "$DATA" 