#!/bin/bash
# A placer dans /usr/www/cgi-bin/apps/moods_sleep.sh
# Eternument, recule les oreilles

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/ears.inc

# Vérifie si le lapin est en veille
if [ -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, rabbit is sleeping."}'
    SendResponse "$DATA"
    exit 0
fi

# Vérifie si les oreilles sont désactivées
if [ -e "$CNF_DATADIR/Run/ears.disabled" ]; then
    DATA='{"return":"1","msg":"Unable to perform action, ears disabled."}'
    SendResponse "$DATA"
    exit 0
fi

# Allume la LED en bleu clair
Leds 0000FF 00FF9F 1 1 2000
EarsMove -5 -5 100
sleep 3

EarsReset
Leds 00FF00 000000 1 1 1000

# Réponse JSON
DATA='{"return":"0","msg":"Sneeze animation completed."}'
SendResponse "$DATA"