#!/bin/sh
# Mood 73 - Vache dans l'étang et marseillaise 
# Durée estimée : 10 secondes

# Vérification si Karotz est en veille
if [ "$(cat /usr/www/cgi-bin/karotz.sleep)" = "1" ]; then
    exit 0
fi

# LEDs : VIOLET et ORANGE en pulsation
/usr/www/cgi-bin/karotz/Leds 660099 FFA500 1 1 800

# Vérification si les oreilles sont désactivées
if [ "$(cat /usr/www/cgi-bin/ears.disabled)" != "1" ]; then
    # Premier mouvement expressif
    /usr/www/cgi-bin/karotz/EarsMove 12 -12 300
    sleep 1
    /usr/www/cgi-bin/karotz/EarsMove -8 8 300
    sleep 1
fi

# Mouvement final si oreilles actives
if [ "$(cat /usr/www/cgi-bin/ears.disabled)" != "1" ]; then
    /usr/www/cgi-bin/karotz/EarsMove 6 6 200
    sleep 0.5
    /usr/www/cgi-bin/karotz/EarsMove -6 -6 200
    sleep 0.5
    /usr/www/cgi-bin/karotz/EarsReset
fi

# LEDs : vertes pour fin propre
/usr/www/cgi-bin/karotz/Leds 00FF00 000000 1 1 1000

exit 0
