#!/bin/bash
# Animation mood 59 - "A c'qu'il paraît, ça arrive tout l'temps..."

# Inclusion des fichiers de configuration et fonctions
source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/ears.inc
source /usr/www/cgi-bin/leds.inc

# Position neutre
EarsReset

# LEDs orange/rose en pulsation
Leds FFA500 FFC0CB 1 1 900
sleep 0.8

# Mouvement 1 - petit hochement curieux
EarsMove -4 4 400
sleep 0.7

# Mouvement 2 - léger basculement
EarsMove 3 -3 400
sleep 0.7

# Fin - LEDs vertes, oreilles neutres
EarsReset
Leds 00FF00 000000 1 1 1000
sleep 1

DATA='{"return":"0","msg":"Mood 59 animation complete."}'
SendResponse "$DATA"
