#!/bin/bash
# Animation mood 82 - "J'suis là ! J'suis plus là !"

# Inclusion des fichiers de configuration et fonctions
source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/ears.inc
source /usr/www/cgi-bin/leds.inc

# Vérifie si le lapin est en veille
if [ -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
    DATA='{"return":"1","msg":"Rabbit is sleeping."}'
    SendResponse "$DATA"
    exit 0
fi

# Vérifie si les oreilles sont désactivées
if [ -e "$CNF_DATADIR/Run/ears.disabled" ]; then
    DATA='{"return":"1","msg":"Ears disabled."}'
    SendResponse "$DATA"
    exit 0
fi

# Position de départ
EarsReset

# LED bleue et violette en pulsation rapide (magique / caché)
Leds 0000FF 660099 1 1 400
sleep 0.4

# Mouvement 1 - "disparaît" (oreilles baissées)
EarsMove 4 4 300
sleep 0.5

# Mouvement 2 - "réapparaît" (oreilles hautes)
EarsMove 15 15 300
sleep 0.5

# Mouvement 3 - "disparaît" à nouveau
EarsMove 4 4 300
sleep 0.5

# Mouvement 4 - "réapparaît"
EarsMove 15 15 300
sleep 0.5

# Mouvement final rapide à l'horizontale (surprise finale)
EarsMove 8 -8 400
sleep 0.4

# Fin : retour au calme
EarsReset
Leds 00FF00 000000 1 1 1000
sleep 1

DATA='{"return":"0","msg":"Mood 82 animation complete."}'
SendResponse "$DATA"
