#!/bin/bash
# Animation "Oui, mais euh, ça reste son ami quand même !" pour le Karotz
# Oreilles qui hésitent puis s'affirment

# Inclusion des fichiers de configuration et des fonctions utilitaires
source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/ears.inc
source /usr/www/cgi-bin/leds.inc

# LED jaune fixe
Leds FFFF00 000000 1 1 1000
sleep 0.5

# Hésitation (0.5-2s)
# Oreilles qui s'inclinent
EarsMove 10 6 15
# LED orange pulsante
Leds FF6600 000000 1 1 500
sleep 1.5

# Affirmation (2-3.5s)
# Oreilles qui se redressent
EarsMove 12 12 15
# LED verte pulsante
Leds 00FF00 000000 1 1 400
sleep 1.5

# Retour à la position initiale
EarsReset
# LED verte fixe
Leds 00FF00 000000 1 1 1000
sleep 0.5

# Réponse JSON
DATA='{"return":"0","msg":"Ami animation completed."}'
SendResponse "$DATA" 