# Configuration des entrées textuelles pour le Nabaztag
input_text:
  nabaztag_ip_address:
    name: Nabaztag Ip Address
    initial: "192.168.1.xxx"  # Adresse IP par défaut du Nabaztag
  nabaztag_color_1:
    name: Nabaztag Color 1
    initial: "ffff00"  # Couleur primaire en hexadécimal (jaune)
  nabaztag_color_2:
    name: Nabaztag Color 2
    initial: "000000"  # Couleur secondaire en hexadécimal (noir)

# État d'éveil du Nabaztag
input_boolean:
  nabaztag_awake:
    initial: on
    
# Configuration des contrôles numériques
input_number:
  nabaztag_ear_left:
    name: Nabaztag Ear Left
    initial: 0
    min: 0
    max: 16  # Position maximale de l'oreille gauche
    step: 1
  nabaztag_ear_right:
    name: Nabaztag Ear Right
    initial: 0
    min: 0
    max: 16  # Position maximale de l'oreille droite
    step: 1
  nabaztag_light_speed:
    name: Nabaztag Light Speed
    initial: 700
    min: 0
    max: 2000  # Vitesse maximale des effets lumineux
    step: 100

# Groupement des contrôles Nabaztag
group:
  nabaztag_utils:
    name: Nabaztag Utils
    entities:
      - script.nabaztag_moods

# Scripts de contrôle du Nabaztag
script:
  nabaztag_moods: 
    alias: "Talk!"  # Fait parler le Nabaztag
    sequence:
      - action: rest_command.nabaztag_moods

  nabaztag_wakeup:
    alias: "Wake Up"  # Réveille le Nabaztag
    sequence:
      - action: rest_command.nabaztag_wakeup
      - action: rest_command.nabaztag_light

  nabaztag_sleep:
    alias: "Sleep"  # Met le Nabaztag en veille
    sequence:
      - action: rest_command.nabaztag_sleep
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.nabaztag_awake

# Interrupteur template pour contrôler l'état d'éveil
switch:
  - platform: template
    switches:
      nabaztag_life:
        friendly_name: "Éveillé"
        value_template: "{{ is_state('input_boolean.nabaztag_awake', 'on') }}"
        turn_on:
          action: script.turn_on
          target:
            entity_id: script.nabaztag_wakeup
        turn_off:
          action: script.turn_on
          target:
            entity_id: script.nabaztag_sleep

# Configuration des commandes REST pour contrôler le Nabaztag
# source : https://www.openkarotz.org/api/
rest_command:
  nabaztag_moods:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/apps/moods"
  nabaztag_wakeup:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/wakeup?silent=1"
  nabaztag_sleep:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/sleep"
  nabaztag_ears_random:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/ears_random"
  nabaztag_ears:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/ears?left={{ states('input_number.nabaztag_ear_left') }}&right={{ states('input_number.nabaztag_ear_right') }}&noreset=1"
  nabaztag_light:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/leds?pulse=1&color={{ states('input_text.nabaztag_color_1') }}&speed={{ states('input_number.nabaztag_light_speed') }}&color2={{ states('input_text.nabaztag_color_2') }}"
# ajout du TTS
  nabaztag_say:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/tts?voice=1&text={{ text }}&nocache=0"
    method: get
    content_type: "application/x-www-form-urlencoded"
# ajout des sons
# sounds : bip1,bling,flush,install_ok,jet1,laser_15,ready,rfid_error,rfid_ok,saut1,start,twang_01,twang_04,return":"0"
  nabaztag_sound:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/sound?id={{ sound }}"

# Capteur pour surveiller l'état de sommeil
sensor:
  - platform: rest
    resource: http://192.168.1.xxx/cgi-bin/status #IP du Karotz
    name: KarotzSleep
    value_template: '{{ value_json.sleep }}'

# ajout de la liste des sons
# input_select:
#   nabaztag_sound_selector:
#     name: Son du Karotz
#     options:
#       - bip1
#       - bling
#       - flush
#       - install_ok
#       - jet1
#       - laser_15
#       - ready
#       - rfid_error
#       - rfid_ok
#       - saut1
#       - start
#       - twang_01
#       - twang_04
#     initial: ready

    
# Automatisations
automation:
  # Gestion de l'état d'éveil
  - alias: "Karotz on"
    trigger:
      - trigger: state
        entity_id: sensor.nabaztag_sleep
        to: "0"
    actions:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.nabaztag_awake

  - alias: "Karotz off"
    trigger:
      trigger: state
      entity_id: sensor.nabaztag_sleep
      to: '1'
    actions:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.nabaztag_awake

  # Mise à jour des couleurs et effets lumineux
  - alias: "Update nabaztag color 1"
    trigger:
      trigger: state       
      entity_id: input_text.nabaztag_color_1
    actions:
      - action: rest_command.nabaztag_light

  - alias: "Update nabaztag color 2"
    trigger:
      - trigger: state
        entity_id: input_text.nabaztag_color_2
    actions:
      - action: rest_command.nabaztag_light

  - alias: "Update nabaztag light speed"
    trigger:
      - trigger: state
        entity_id: input_number.nabaztag_light_speed
    actions:
      - action: rest_command.nabaztag_light

  # Mise à jour de la position des oreilles
  - alias: "Update nabaztag ear left"
    trigger:
      - trigger: state
        entity_id: input_number.nabaztag_ear_left
    actions:
      - action: rest_command.nabaztag_ears

  - alias: "Update nabaztag ear right"
    trigger:
      - trigger: state
        entity_id: input_number.nabaztag_ear_right
    actions:
      - action: rest_command.nabaztag_ears

  # Automatisations basées sur la température
  - alias: Température sous -10
    description: 'Change la couleur en bleu foncé quand il fait très froid'
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      below: -10
    actions:
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_1
        value: "1a00ff"  # Bleu foncé
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_2
        value: "000000"  # Noir
      
  - alias: Température de -10 à 0
    description: 'Change la couleur en bleu clair pour les températures froides'
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: -10
      below: 0
    actions:
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_1
        value: "003cff"  # Bleu clair
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  - alias: Température de 0 à 10
    description: 'Change la couleur en vert pour les températures fraîches'
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: 0
      below: 10
    actions:
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_1
        value: "00FF00"  # Vert
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  - alias: Température de 10 à 20
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: 10
      below: 20
    actions:
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_1
        value: "62ff00"
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  - alias: Température de 20 à 30
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: 20
      below: 30
    actions:
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_1
        value: "ff9100"
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  - alias: Température supérieure à 30
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: 30
    actions:
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_1
        value: "ff0000"
    - action: input_text.set_value
      data:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  # Automatisations basées sur les risques de pluie
  - alias: Risque de pluie < 40%
    description: 'Mouvements aléatoires des oreilles pour faible risque de pluie'
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/15'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_rain_chance
      above: 10
      below: 40
    actions:
    - action: rest_command.nabaztag_ears_random
      
  - alias: Risque de pluie de 40% à 60%
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_rain_chance
      above: 40
      below: 60
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_ear_left
        value: 15
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_ear_right
        value: 1
      
  - alias: Risque de pluie > 60%
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_rain_chance
      above: 60
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_ear_left
        value: 9
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_ear_right
        value: 13
      
  # Automatisations basées sur la vitesse du vent
  - alias: Wind 0
    description: 'Vitesse de clignotement très lente pour vent calme'
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      below: 1
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 2000  # Clignotement très lent

  - alias: Wind 1
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 1
      below: 5
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 1834
      
  - alias: Wind 2
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 6
      below: 11
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 1668
      
  - alias: Wind 3
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 12
      below: 19
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 1502
      
  - alias: Wind 4
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 20
      below: 28
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 1336
      
  - alias: Wind 5
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 29
      below: 38
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 1170
      
  - alias: Wind 6
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 39
      below: 49
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 1004
      
  - alias: Wind 7
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 50
      below: 61
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 838
      
  - alias: Wind 8
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 62
      below: 74
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 672
      
  - alias: Wind 9
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 75
      below: 88
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 506
      
  - alias: Wind 10
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 89
      below: 102
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 340
      
  - alias: Wind 11
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 103
      below: 117
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 174
      
  - alias: Wind 12
    description: ''
    trigger:
    - trigger: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 118
    actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.nabaztag_light_speed
        value: 8
