# Annonce le niveau de batterie via le LLM et le Karotz_dev.

alias: "Karotz_dev - Annonce du niveau de batterie"
description: Annonce le niveau de batterie actuel
triggers:
  - minutes: "/15"
    trigger: time_pattern

conditions:
  - condition: time
    after: "08:00:00"
    before: "20:00:00"
  - type: is_battery_level
    condition: device
    device_id: ff0cfc95d1ceb474b8cc0f2d1281dd48
    entity_id: 4ee0d5305c03de681602dfd28c985e92
    domain: sensor
    above: 90

actions:
  - action: conversation.process
    data:
      text: >-
        Le niveau actuel de batterie est de {{ states('sensor.victron_battery_soc')
        | float(0) | round(0) }} pour cent. Annonce ce pourcentage en une phrase
        courte et naturelle.
      agent_id: conversation.llama3_1
    response_variable: llm_response

  - action: rest_command.karotz_dev_say
    data:
      text: "{{ llm_response.response.speech.plain.speech }}"

mode: single
